import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { createWorker } from '../worker/index.js';
import { HttpError } from '../worker/claims.js';
test('listing requests require a verified personal identity, persist idempotently, and do not create claims', async () => {
  const db = new DatabaseSync(':memory:');
  for (const file of ['0001_claims.sql', '0002_portfolios.sql']) db.exec(readFileSync(new URL('../migrations/' + file, import.meta.url), 'utf8'));
  const env = { CLERK_PUBLISHABLE_KEY: 'test', CLERK_SECRET_KEY: 'test', APP_ORIGIN: 'https://starboard.test', DB: { prepare(sql) { return { bind(...args) { return { first: async () => db.prepare(sql).get(...args), run: async () => db.prepare(sql).run(...args) }; } }; } } };
  let user = { id: 'owner', externalAccounts: [{ provider: 'github', providerUserId: '123', verification: { status: 'verified' } }] }, githubCalls = 0, profile = { id: 123, type: 'User', login: 'current-login' };
  const worker = createWorker({ getUser: async request => { if (!request.headers.has('Authorization')) throw new HttpError(401, 'Sign in'); return user; }, githubFetch: async url => { assert.equal(url, 'https://api.github.com/user/123'); githubCalls++; return Response.json(profile); } });
  const call = (headers = {}) => worker.fetch(new Request('https://starboard.test/api/listing-request', { method: 'POST', headers: { Origin: env.APP_ORIGIN, Authorization: 'test', ...headers } }), env);
  assert.equal((await call({ Origin: 'https://other.test' })).status, 403);
  user.externalAccounts[0].verification.status = 'unverified';
  assert.equal((await call()).status, 403); assert.equal(githubCalls, 0);
  user.externalAccounts[0].verification.status = 'verified';
  profile.type = 'Organization'; assert.equal((await call()).status, 400);
  profile.type = 'User';
  const saved = await (await call()).json();
  assert.equal(saved.status, 'requested'); assert.equal(saved.login, 'current-login');
  const count = githubCalls; assert.equal((await call()).status, 200); assert.equal(githubCalls, count);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM listing_requests').get().n, 1);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM profile_claims').get().n, 0);
  assert.ok(!JSON.stringify(saved).includes('owner'));
  user.id = 'different-clerk-user'; assert.equal((await call()).status, 409);
  delete env.CLERK_SECRET_KEY; assert.equal((await call()).status, 503);
  db.close();
});
