import { progress } from './milestones.mjs';
import { shareButton, followButton } from './engagement-pages.mjs';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const num = value => new Intl.NumberFormat('en-US').format(value);
export const joinCTA = '<a class="profile-button claim-primary" href="/join/">Get your builder page →</a>';

export function milestoneCard(event) {
  return { key: event.id, developerId: event.developerId, title: event.project, primary: `★ ${num(event.threshold)}`,
    secondary: `A project milestone for ${event.login}`, scope: 'First crossing observed by Starboard · GitHub stars',
    date: `${event.from.slice(0, 10)} → ${event.to.slice(0, 10)}`, path: event.path,
    text: `${event.project} passed ${num(event.threshold)} GitHub stars between Starboard observations on ${event.from.slice(0, 10)} and ${event.to.slice(0, 10)}.\nExplore the project and the work of GitHub builder ${event.login}.`, source: event.source };
}
export function reportCard(report) {
  const leader = report.entries[0];
  if (report.status !== 'ready' || !leader || leader.gain <= 0) return null;
  return { key: `report-${report.kind}-${report.startDate}`, title: `${report.kind === 'week' ? 'Weekly' : 'Monthly'} roundup`, primary: `+${num(leader.gain)}`,
    secondary: `${leader.login} · #1${report.entries.filter(e => e.rank === 1).length > 1 ? ' (tied)' : ''} · ${report.entries.length} comparable builders`,
    scope: 'Net stars on matched projects · Curated sample', date: `${report.startDate} → ${report.endDate}`, path: report.path,
    text: `Starboard's ${report.kind} of ${report.startDate}: ${leader.login} ${report.entries.filter(e => e.rank === 1).length > 1 ? 'shares the lead' : 'leads'} with +${num(leader.gain)} net stars on matched projects.\n${report.entries.length} comparable builders in our curated sample. Observations: ${report.startDate}–${report.endDate}.` };
}
export function milestoneProgress(repo) {
  const p = progress(repo.stargazers_count);
  return `<div class="milestone-progress"><span class="eyebrow">THE NEXT MILESTONE</span><h2>${p.next ? `${num(p.remaining)} stars to ${num(p.next)}.` : `${num(p.reached)} stars and counting.`}</h2><progress max="100" value="${p.percent}" aria-label="Progress toward next GitHub star milestone">${p.percent}%</progress><p>${num(p.stars)} stars in this snapshot${p.reached ? ` · ${num(p.reached)}-star threshold met` : ''}. A current total does not establish when a milestone was reached.</p></div>`;
}
export function portfolioMilestones(developer, events) {
  const repos = developer.repos.filter(r => !r.archived).slice().sort((a, b) => {
    const pa = progress(a.stargazers_count), pb = progress(b.stargazers_count);
    return pb.percent - pa.percent || b.stargazers_count - a.stargazers_count;
  }).slice(0, 3);
  const earned = events.filter(e => e.developerId === developer.id).slice(0, 3);
  return `<section class="page-section"><div class="section-heading"><h2>Small steps. Public progress.</h2><a href="/milestones/">Milestone feed →</a></div><div class="milestone-grid">${repos.map(repo => `<article class="story-card"><a href="/projects/${repo.full_name.toLowerCase().split('/').map(encodeURIComponent).join('/')}/">${esc(repo.name)} →</a>${milestoneProgress(repo)}</article>`).join('')}</div>${earned.length ? `<h3>Observed achievements</h3>${earned.map(e => `<p>${esc(e.project)} passed ${num(e.threshold)} stars · ${e.to.slice(0, 10)} ${shareButton(e.id)}</p>`).join('')}` : '<p class="page-note">New achievements will appear after we observe a project crossing a threshold. Following this builder keeps their portfolio close.</p>'}</section>`;
}
export function milestonePage(events) {
  return { path: '/milestones/', title: 'Open source project milestones — Starboard', description: 'Celebrate observed GitHub star milestones and discover the developers behind open source projects.', crumbs: [['Milestones']], index: events.length > 0,
    body: `<div class="page-intro"><span class="eyebrow">EVERY BUILDER STARTS AT ZERO</span><h1>Celebrate the <span>next step.</span></h1><p>Ten stars or ten thousand. Give the work, and the person behind it, a moment in the spotlight.</p></div>${events.length ? `<div class="story-grid">${events.slice(0, 100).map(e => `<article class="story-card"><span class="eyebrow">FIRST CROSSING OBSERVED</span><h2>★ ${num(e.threshold)}</h2><a href="${e.path}">${esc(e.project)} →</a><p>Observed between ${e.from.slice(0, 10)} and ${e.to.slice(0, 10)}.</p><p>GitHub owner: <a href="${e.developerPath}">${esc(e.login)}</a></p><div class="profile-actions">${followButton(e.developerId)}${shareButton(e.id)}</div></article>`).join('')}</div>` : '<section class="competition-empty"><span class="collection-badge">Collecting history</span><h2>The first achievements are ahead of us.</h2><p>We have a starting snapshot. A new milestone needs a later observation of the same project with the same owner crossing a threshold.</p><a class="profile-button" href="/developers/">Find a builder to follow →</a></section>'}<aside class="page-provenance"><strong>Earned attention, with evidence.</strong><p>Thresholds start at 10 stars. We only announce the first observed crossing beyond a project’s previous highest observed count. Imports, ownership transfers, and re-crossing an old threshold do not create new achievements. Observation dates describe a window, not the exact time a star arrived.</p></aside>${joinCTA}` };
}
export function reportPage(report) {
  const card = reportCard(report);
  return { path: report.path, title: `${report.kind === 'week' ? 'Weekly' : 'Monthly'} open source roundup: ${report.startDate} — Starboard`, description: `Developer star gains for the calendar ${report.kind} ${report.startDate} through ${report.labelEnd}, using comparable GitHub observations.`, crumbs: [['Reports', '/reports/'], [report.startDate]], index: report.status === 'ready',
    body: `<div class="page-intro"><span class="eyebrow">THE COMPLETED ${report.kind.toUpperCase()}</span><h1>${report.startDate} <span>→ ${report.labelEnd}</span></h1><p>A recurring look at public work gaining attention.</p><a href="/reports/">All roundups →</a></div>${report.status === 'ready' ? `<p>${report.entries.length} comparable developers · ${report.excludedDevelopers} without coverage.</p><ol class="climb-list">${report.entries.map(e => `<li><span class="climb-rank">#${e.rank}</span><div class="climb-person"><a href="${esc(e.profilePath)}">${esc(e.name)}</a><small>${e.matched} matched projects · ${e.added} additions / ${e.removed} removals excluded</small></div><div class="climb-gain"><strong>${e.gain > 0 ? '+' : ''}${num(e.gain)}</strong><small>net stars</small></div>${followButton(e.id)}</li>`).join('')}</ol>${card ? shareButton(card.key) : ''}` : `<section class="competition-empty"><h2>This period needs more history.</h2><p>We need complete observations on both ${report.startDate} and ${report.endDate}. There are no standings to announce yet.</p><a href="/trending/week/">Follow the current climb →</a></section>`}<aside class="page-provenance"><strong>Calendar period, measured at snapshot boundaries.</strong><p>Weeks run Monday–Sunday in UTC; months use calendar dates. Net stars compare snapshots on the starting day and the next period’s starting day. ${report.startObservedAt ? `Actual observations: ${esc(report.startObservedAt)} → ${esc(report.endObservedAt)}.` : 'Boundary observations are not yet available.'} These are not exact midnight counts. Only repositories with matching IDs and owners at both boundaries contribute. Ties share rank; negative changes count.</p><a href="/#methodology">Full methodology →</a></aside>` };
}
export function reportsPage(items) {
  return { path: '/reports/', title: 'Weekly and monthly open source roundups — Starboard', description: 'Completed calendar-week and calendar-month reports of developer progress on Starboard.', crumbs: [['Reports']], index: items.some(r => r.status === 'ready'),
    body: `<div class="page-intro"><span class="eyebrow">A REASON TO RETURN</span><h1>The open source <span>roundup.</span></h1><p>Completed weeks and months. Come back for the builders making progress and the projects behind their climb.</p><nav class="competition-tabs"><a href="/trending/week/">Rolling 7 days</a><a href="/trending/month/">Rolling 30 days</a><a href="/milestones/">Project milestones</a></nav></div><div class="story-grid">${items.map(r => `<article class="story-card"><span class="eyebrow">${r.kind === 'week' ? 'WEEKLY' : 'MONTHLY'} ROUNDUP</span><h2><a href="${r.path}">${r.startDate} → ${r.labelEnd}</a></h2><p>${r.status === 'ready' ? `${r.entries.length} comparable builders · final period` : 'Collecting boundary observations'}</p></article>`).join('')}</div>` };
}
export function joinPage() {
  return { path: '/join/', title: 'Get your open source builder page — Starboard', description: 'Find your GitHub portfolio, claim your work, and share project milestones on Starboard.', crumbs: [['Get your page']],
    body: `<div class="page-intro"><span class="eyebrow">YOUR WORK DESERVES A HOME</span><h1>You build it.<br><span>Let people find it.</span></h1><p>Your open source projects, your story, and your next milestone. One page to put in your bio.</p></div><section class="join-panel"><form id="join-form"><label for="join-login">Your GitHub username</label><div class="join-input"><span>github.com/</span><input id="join-login" name="login" required pattern="[A-Za-z0-9][A-Za-z0-9-]{0,38}" maxlength="39" autocomplete="username" placeholder="yourname"><button class="profile-button claim-primary">Find my page →</button></div></form><p id="join-status" role="status">Already listed? Your portfolio is ready to explore. New builders can request a listing after connecting GitHub.</p><button id="join-request" class="profile-button" hidden>Request my listing →</button><noscript>Enable JavaScript to find or request your page, or <a href="/developers/">browse the developer directory</a>.</noscript></section><div class="story-grid join-steps"><article class="story-card"><span class="eyebrow">01 · YOUR PROJECTS</span><h2>Show what you ship.</h2><p>Public, licensed projects from your personal GitHub account. Real stars and direct links to your work.</p></article><article class="story-card"><span class="eyebrow">02 · YOUR STORY</span><h2>Make the page yours.</h2><p>Verify your GitHub account, explain what you build, and feature the projects you want people to try.</p></article><article class="story-card"><span class="eyebrow">03 · YOUR PROGRESS</span><h2>Give people a reason to return.</h2><p>Follow builders, share observed milestones, and see your place in the weekly climb. Sharing never changes your score.</p></article></div><p class="page-note">Listings are reviewed for eligibility before import. Requesting a listing does not reserve a username or guarantee inclusion. Claiming verifies GitHub account control, not original authorship of every project.</p>` };
}

export function announcementHistory(ledger) {
  const published = ledger.filter(item => item.status === 'published' && /^https:\/\/(x\.com|twitter\.com)\/[A-Za-z0-9_]+\/status\/\d+$/.test(item.postUrl || '') && Number.isFinite(Date.parse(item.publishedAt)))
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
  return { path: '/announcements/', title: 'Starboard announcement history', description: 'Published Starboard project milestones, developer spotlights, and recurring roundups.', crumbs: [['Announcements']], index: published.length > 0,
    body: `<div class="page-intro"><span class="eyebrow">PUBLIC WORK, SHARED</span><h1>The announcement <span>archive.</span></h1><p>Project milestones and builder stories published by Starboard. Prepared drafts appear here only after a published post is recorded.</p></div>${published.length ? `<div class="story-grid">${published.map(item => `<article class="story-card"><span class="eyebrow">${item.publishedAt.slice(0, 10)}</span><h2>${esc(item.title)}</h2><p class="story-draft">${esc(item.text)}</p><a class="profile-button" href="${esc(item.postUrl)}" rel="noopener noreferrer" target="_blank">Read published post ↗</a></article>`).join('')}</div>` : '<section class="competition-empty"><h2>The first post is still ahead.</h2><p>No published announcements have been recorded yet.</p><a href="/share/">Explore stories to share →</a></section>'}${joinCTA}` };
}
